export const siteContent = {
  site: {
    name: "VCRUNYUE",
    locale: "zh-CN",
    domain: "https://vcrunyue.com",
    title: "Vcrunyue Portfolio",
    description:
      "个人展示网站，记录我的创作、技术实践、游戏与音乐项目，以及长期兴趣收藏。",
    tagline: "感谢访问我的个人网站，希望你能找到感兴趣的内容。",
    taglineHighlight: "",
  },
  socialLinks: [
    {
      platform: "GitHub",
      label: "GitHub",
      iconKey: "github",
      url: "https://github.com/SamuelQZQ",
    },
    {
      platform: "Twitter/X",
      label: "Twitter/X",
      iconKey: "twitter",
      url: "https://x.com/SamuelQZQ",
    },
    {
      platform: "Bilibili",
      label: "Bilibili",
      iconKey: "bilibili",
      url: "https://space.bilibili.com/4848323",
    },
    {
      platform: "Douyin",
      label: "Douyin",
      iconKey: "tiktok",
      url: "https://www.douyin.com/user/MS4wLjABAAAAcBGY4RqDTLberZGiFTk-nG_L0hVwrFC7Bii_20YdBgBDGu-9JoA2L6jtkpdnpBpr",
    },
  ],
  navLinks: [
    { label: "博客", href: "#blog" },
    { label: "游戏", href: "#game" },
    { label: "音乐", href: "#music" },
    { label: "图片", href: "#images" },
    { label: "收藏", href: "#favorites" },
  ],
  sections: {
    blog: [
      {
        title: "把 AI 真正接进日常创作",
        date: "2026-04-01",
        summary:
          "记录我怎样把检索、整理、初稿和复盘拆成可复用流程，让 AI 真的成为日常工作的一部分。",
        cover: "/assets/blog/blog-react.webp",
        url: "https://openai.com/",
        category: "AI",
        tags: ["AI", "工作流", "创作"],
      },
      {
        title: "AI 工作流的输入输出设计",
        date: "2026-03-15",
        summary:
          "比起不断叠加工具，我更关心输入格式、上下文组织和交付标准如何让结果稳定下来。",
        cover: "/assets/blog/blog-frontend.webp",
        url: "https://platform.openai.com/docs",
        category: "AI",
        tags: ["AI", "效率", "方法论"],
      },
      {
        title: "从钱包到签名：一次讲清 Web3 基础操作",
        date: "2026-03-01",
        summary:
          "把钱包、签名、授权和链上交互拆成几步看，Web3 的基础路径其实没有想象中那么绕。",
        cover: "/assets/blog/blog-nomad.webp",
        url: "https://ethereum.org/",
        category: "Web3",
        tags: ["Web3", "钱包", "基础"],
      },
      {
        title: "链上身份能不能成为长期内容资产",
        date: "2026-02-15",
        summary:
          "从所有权、公开可验证和可迁移性出发，梳理链上身份与长期写作之间真正有价值的连接点。",
        cover: "/assets/blog/blog-tech-life.webp",
        url: "https://ethereum.org/en/web3/",
        category: "Web3",
        tags: ["Web3", "身份", "内容"],
      },
      {
        title: "前端工程师也该懂的 DNS 与 HTTPS",
        date: "2026-02-01",
        summary:
          "把域名解析、证书、CDN 和缓存串成一条线，线上排障时就不会只盯着页面本身发呆。",
        cover: "/assets/blog/blog-performance.webp",
        url: "https://developers.cloudflare.com/dns/",
        category: "网络基础",
        tags: ["网络基础", "DNS", "HTTPS"],
      },
      {
        title: "家庭网络排障清单",
        date: "2026-01-20",
        summary:
          "整理光猫、路由器、Wi-Fi 干扰、DNS 与端口转发这些最常见的问题定位顺序，尽量少走弯路。",
        cover: "/assets/blog/blog-frontend.webp",
        url: "https://www.cloudflare.com/learning/dns/what-is-dns/",
        category: "网络基础",
        tags: ["网络基础", "排障", "家庭网络"],
      },
      {
        title: "一台创作主机的装机思路",
        date: "2026-01-10",
        summary:
          "从 CPU、显卡、内存、硬盘与散热预算出发，讨论一套更平衡而不是只堆参数的配置方式。",
        cover: "/assets/blog/blog-tech-life.webp",
        url: "https://www.tomshardware.com/",
        category: "电脑装机",
        tags: ["电脑装机", "硬件", "配置"],
      },
      {
        title: "显示器、键盘与桌面效率",
        date: "2025-12-26",
        summary:
          "长时间写作、剪辑和开发时，哪些外设升级真的能改变工作体验，哪些只是看起来更专业。",
        cover: "/assets/blog/blog-performance.webp",
        url: "https://www.rtings.com/monitor",
        category: "电脑装机",
        tags: ["电脑装机", "外设", "效率"],
      },
      {
        title: "技术与生活的平衡",
        date: "2025-12-12",
        summary:
          "从训练安排、创作节奏和时间块管理三个角度总结，怎样把深度工作和生活体验放在同一条主线上。",
        cover: "/assets/blog/blog-tech-life.webp",
        url: "https://www.strongerbyscience.com/",
        category: "运动健身",
        tags: ["运动健身", "节奏", "生活方式"],
      },
      {
        title: "恢复比训练更难：一周节奏记录",
        date: "2025-11-28",
        summary:
          "记录训练量、睡眠和工作强度如何互相牵制，以及我怎样调整每周节奏避免长期透支。",
        cover: "/assets/blog/blog-nomad.webp",
        url: "https://www.precisionnutrition.com/",
        category: "运动健身",
        tags: ["运动健身", "恢复", "训练"],
      },
      {
        title: "日常补剂怎么做减法",
        date: "2025-11-15",
        summary:
          "不追求堆满一桌瓶瓶罐罐，而是从目标、饮食结构和反馈出发，做更克制的补剂选择。",
        cover: "/assets/blog/blog-react.webp",
        url: "https://examine.com/",
        category: "营养补剂",
        tags: ["营养补剂", "补剂", "饮食"],
      },
      {
        title: "训练期饮食和补剂安排复盘",
        date: "2025-11-01",
        summary:
          "把蛋白质、碳水、肌酸和电解质的使用场景拆开看，减少跟风式补充带来的混乱。",
        cover: "/assets/blog/blog-performance.webp",
        url: "https://www.healthline.com/nutrition/sports-nutrition-guide",
        category: "营养补剂",
        tags: ["营养补剂", "训练", "恢复"],
      },
    ],
    game: [
      {
        title: "Black Myth: Wukong",
        summary: "以中国神话为背景的动作角色扮演游戏。你将扮演“天命人”，揭开昔日英雄传奇背后的真相。",
        posterColor: "linear-gradient(135deg, #111827 0%, #3f2b16 52%, #f59e0b 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "It Takes Two",
        summary: "纯粹为合作设计的平台冒险游戏。通过多样化的玩法，讲述了一段关于修补家庭关系的感人故事。",
        cover: "/assets/games/it-takes-two.jpeg",
        posterColor: "linear-gradient(135deg, #f97316 0%, #fb7185 100%)",
        featuredOnHome: true,
        featuredOrder: 2,
      },
      {
        title: "Ghostrunner",
        summary: "第一人称视角的硬核赛博朋克动作游戏。动作迅猛，强调一击必杀的极限战斗体验。",
        posterColor: "linear-gradient(135deg, #0f172a 0%, #1d4ed8 50%, #22d3ee 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Titanfall 2",
        summary: "顶尖的第一人称射击游戏。讲述了铁驭与泰坦之间深厚的情感羁绊以及震撼的科幻战争。",
        posterColor: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 58%, #f97316 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Hellblade: Senua's Sacrifice",
        summary: "深入探索精神疾病的心理动作游戏。跟随塞娜进入凯尔特神话的深渊，进行一场痛苦的救赎旅程。",
        posterColor: "linear-gradient(135deg, #111827 0%, #374151 48%, #6b7280 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Portal",
        summary: "Valve 开发的经典解谜游戏。利用传送门枪在空间中穿梭，挑战物理定律并面对 AI 的嘲讽。",
        posterColor: "linear-gradient(135deg, #e2e8f0 0%, #cbd5e1 55%, #fb923c 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "To the Moon",
        summary: "催泪向剧情神作。两名医生通过改变记忆，为一个垂死的老人完成去月球的最后心愿。",
        posterColor: "linear-gradient(135deg, #0f172a 0%, #312e81 52%, #93c5fd 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Journey",
        summary: "艺术化的禅意冒险游戏。在无垠的沙漠中独自旅行或与陌生人偶遇，体验纯粹的情感波动。",
        cover: "/assets/games/journey.jpeg",
        posterColor: "linear-gradient(135deg, #fbbf24 0%, #fb923c 55%, #fef3c7 100%)",
        featuredOnHome: true,
        featuredOrder: 9,
      },
      {
        title: "GRIS",
        summary: "绝美的平台解谜游戏。通过色彩的恢复，讲述女孩在痛苦中找回自我、克服心理创伤的过程。",
        cover: "/assets/games/gris.jpg",
        posterColor: "linear-gradient(135deg, #d1d5db 0%, #94a3b8 55%, #fbcfe8 100%)",
        featuredOnHome: true,
        featuredOrder: 1,
      },
      {
        title: "ABZU",
        summary: "唯美的深海潜水游戏。探索色彩斑斓的海底世界并与数以千计的生物互动，节奏宁静且治愈。",
        cover: "/assets/games/abzu.jpeg",
        posterColor: "linear-gradient(135deg, #0f766e 0%, #0891b2 55%, #67e8f9 100%)",
        featuredOnHome: true,
        featuredOrder: 8,
      },
      {
        title: "THE FINALS",
        summary: "环境可全破坏的快节奏竞技射击游戏。玩家在虚拟竞技场中组队争夺财富，极度强调地形破坏与战术搭配。",
        cover: "/assets/games/the-finals.jpg",
        posterColor: "linear-gradient(135deg, #b91c1c 0%, #ef4444 55%, #f97316 100%)",
        featuredOnHome: true,
        featuredOrder: 3,
      },
      {
        title: "Brotato",
        summary: "顶级俯视角竞技场射击轻度 Rogue 游戏。玩家扮演一只可同时手持 6 种武器的土豆，在异星怪物的包围中生存。",
        posterColor: "linear-gradient(135deg, #92400e 0%, #d97706 55%, #facc15 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Patrick's Parabox",
        summary: "屡获殊荣的递归解谜游戏。将“推箱子”机制推向极致，玩家在无限循环的逻辑空间中进出箱体。",
        cover: "/assets/games/parabox.jpeg",
        posterColor: "linear-gradient(135deg, #166534 0%, #10b981 55%, #a7f3d0 100%)",
        featuredOnHome: true,
        featuredOrder: 7,
      },
      {
        title: "Getting Over It with Bennett Foddy",
        summary: "极具挫败感的物理攀爬游戏。玩家仅靠一把长柄榔头操控瓮中人，在重力与物理碰撞的折磨下登顶。",
        posterColor: "linear-gradient(135deg, #1f2937 0%, #4b5563 55%, #9ca3af 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Raft",
        summary: "海上生存冒险游戏。玩家从一小块木板开始，通过打捞垃圾、扩建木筏，在危机四伏的大海中建立家园。",
        posterColor: "linear-gradient(135deg, #0369a1 0%, #0ea5e9 55%, #7dd3fc 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "URBO",
        summary: "极简风格的禅意城市建设解谜游戏。通过在方格盘上组合房屋使建筑升级，在轻快节奏中规划微缩都市。",
        posterColor: "linear-gradient(135deg, #e5e7eb 0%, #cbd5e1 55%, #93c5fd 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "The Forest",
        summary: "经典恐怖生存游戏。玩家在坠机后落入神秘森林，必须伐木建房、狩猎求生，并对抗潜伏的变异食人族。",
        posterColor: "linear-gradient(135deg, #14532d 0%, #166534 55%, #4d7c0f 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "FAR: Lone Sails",
        summary: "具有末世氛围的载具旅行游戏。玩家驾驶巨大的混合动力车在干涸海床上逆风而行，探寻文明遗迹。",
        posterColor: "linear-gradient(135deg, #78350f 0%, #d97706 55%, #fde68a 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Chained Together",
        summary: "多人协作攀爬游戏。玩家们被铁链锁在一起，必须同步跳跃与攀爬以逃离地狱，极度考验团队默契。",
        posterColor: "linear-gradient(135deg, #312e81 0%, #6366f1 55%, #c4b5fd 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "World of Goo",
        summary: "经典物理益智游戏。利用各种属性的“粘粘球”搭建桥梁或塔楼，通过力学设计将球送入管道。",
        cover: "/assets/games/world-of-goo.jpeg",
        posterColor: "linear-gradient(135deg, #111827 0%, #1f2937 55%, #f59e0b 100%)",
        featuredOnHome: true,
        featuredOrder: 4,
      },
      {
        title: "Sable",
        summary: "独特的莫比乌斯画风开放世界冒险游戏。玩家扮演名为沙贝的少女，穿梭于广袤的沙漠与古老残骸之间，展开一场关于自我发现的成年礼。",
        cover: "/assets/games/sable.jpeg",
        posterColor: "linear-gradient(135deg, #f5d0b5 0%, #f8dcc7 55%, #fef3c7 100%)",
        featuredOnHome: true,
        featuredOrder: 5,
      },
      {
        title: "OUROS",
        summary: "平静柔和的曲线拼图游戏。玩家通过拖动节点改变曲线路径，让光球顺利通过所有目标点，极具美感。",
        posterColor: "linear-gradient(135deg, #0f766e 0%, #22d3ee 55%, #ecfeff 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Hook / Hook 2",
        summary: "极简主义逻辑解谜系列。玩家需按正确顺序拆解由钩子、连线和机关组成的复杂结构，过程解压。",
        posterColor: "linear-gradient(135deg, #f8fafc 0%, #cbd5e1 55%, #64748b 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "The Henry Stickmin Collection",
        summary: "互动式动画冒险合集。通过无厘头的选择引导主角亨利完成任务，包含大量爆笑死法与致敬彩蛋。",
        posterColor: "linear-gradient(135deg, #be123c 0%, #ef4444 55%, #fecaca 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Buckshot Roulette",
        summary: "高风险桌面赌博游戏。在阴暗后巷与恶魔对赌，使用改制散弹枪进行生死角逐，心理战极强。",
        posterColor: "linear-gradient(135deg, #052e16 0%, #166534 55%, #65a30d 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "LIMBO",
        summary: "黑白剪影风格解谜平台游戏。玩家扮演小男孩在充满陷阱和巨大生物的阴森世界寻找姐姐，气氛压抑。",
        posterColor: "linear-gradient(135deg, #020617 0%, #334155 55%, #94a3b8 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "12 is Better Than 6",
        summary: "钢笔画风格的硬核俯视角射击游戏。以 1873 年美国西部为背景，强调精准击杀与潜行，小众精品。",
        posterColor: "linear-gradient(135deg, #451a03 0%, #92400e 55%, #fcd34d 100%)",
        featuredOnHome: false,
        featuredOrder: null,
      },
      {
        title: "Hue",
        summary: "着色解谜平台游戏。玩家通过改变世界背景颜色使障碍物显现或消失，在灰色世界中寻找失踪的母亲。",
        cover: "/assets/games/hue.jpeg",
        posterColor: "linear-gradient(135deg, #ef4444 0%, #f59e0b 24%, #eab308 40%, #22c55e 58%, #06b6d4 78%, #8b5cf6 100%)",
        featuredOnHome: true,
        featuredOrder: 6,
      },
    ],
    music: [
      {
        title: "ReturnTrue Band",
        summary: "程序员摇滚项目，关注编曲表达和舞台叙事。",
        cover: "/assets/music/music-gif.gif",
        url: "https://youtube.com/shorts/nvCqd36_RYQ",
      },
      {
        title: "Suhr Modern Satin",
        summary: "电吉他音色记录与演奏片段，持续打磨动态控制。",
        cover: "/assets/music/music-cover.webp",
        url: "https://www.suhr.com/electric-guitars/modern/",
      },
      {
        title: "Arturia MicroFreak",
        summary: "硬件合成器音色实验，探索 texture 与节奏结构。",
        cover: "/assets/music/music-cover.webp",
        url: "https://www.arturia.com/products/hardware-synths/microfreak/overview",
      },
    ],
    images: [
      {
        title: "城市风光",
        desc: "以建筑线条和光影层次呈现现代城市空间节奏。",
        image: "/assets/images/photo-1.webp",
        url: "https://www.behance.net/",
        category: "摄影",
      },
      {
        title: "自然景观",
        desc: "记录山海、云层与天气变化形成的自然秩序。",
        image: "/assets/images/photo-2.webp",
        url: "https://www.nationalgeographic.com/photography",
        category: "自然",
      },
      {
        title: "创意设计",
        desc: "从形状、材质与排版关系中寻找视觉表达的平衡。",
        image: "/assets/images/photo-3.webp",
        url: "https://dribbble.com/",
        category: "设计",
      },
      {
        title: "街头摄影",
        desc: "捕捉日常空间中的人、光、动势与临场感。",
        image: "/assets/images/photo-4.webp",
        url: "https://www.magnumphotos.com/",
        category: "街拍",
      },
      {
        title: "科技产品",
        desc: "关注产品结构、工业设计与交互细节的一致性。",
        image: "/assets/images/photo-5.webp",
        url: "https://www.theverge.com/tech",
        category: "科技",
      },
      {
        title: "旅行见闻",
        desc: "记录不同文化和地理空间带来的体验差异。",
        image: "/assets/images/photo-6.webp",
        url: "https://www.lonelyplanet.com/",
        category: "旅行",
      },
    ],
    favorites: [
      {
        group: "书籍",
        items: [
          {
            title: "Atomic Habits",
            subtitle: "James Clear",
            desc: "通过小步迭代构建长期复利习惯。",
            cover: "/assets/favorites/books/book-1.webp",
            url: "https://www.goodreads.com/book/show/40121378-atomic-habits",
          },
          {
            title: "Clean Code",
            subtitle: "Robert C. Martin",
            desc: "面向可维护性的代码组织与工程纪律。",
            cover: "/assets/favorites/books/book-2.webp",
            url: "https://www.goodreads.com/book/show/3735293-clean-code",
          },
          {
            title: "Designing Data-Intensive Applications",
            subtitle: "Martin Kleppmann",
            desc: "数据系统设计中的一致性、扩展与可靠性。",
            cover: "/assets/favorites/books/book-3.webp",
            url: "https://www.goodreads.com/book/show/23463279-designing-data-intensive-applications",
          },
        ],
      },
      {
        group: "电影",
        items: [
          {
            title: "Inception",
            subtitle: "Christopher Nolan",
            desc: "在叙事结构与视觉表达上建立多层现实体验。",
            cover: "/assets/favorites/movies/movie-1.webp",
            url: "https://www.imdb.com/title/tt1375666/",
          },
          {
            title: "Interstellar",
            subtitle: "Christopher Nolan",
            desc: "将科学设定与情感叙事进行高密度融合。",
            cover: "/assets/favorites/movies/movie-2.webp",
            url: "https://www.imdb.com/title/tt0816692/",
          },
          {
            title: "The Matrix",
            subtitle: "The Wachowskis",
            desc: "关于现实与系统边界的经典科幻表达。",
            cover: "/assets/favorites/movies/movie-3.webp",
            url: "https://www.imdb.com/title/tt0133093/",
          },
        ],
      },
      {
        group: "工具",
        items: [
          {
            title: "Visual Studio Code",
            subtitle: "Code Editor",
            desc: "高扩展性的开发编辑器。",
            cover: "/window.svg",
            url: "https://code.visualstudio.com/",
          },
          {
            title: "Figma",
            subtitle: "Design Tool",
            desc: "高效协作与界面设计工具。",
            cover: "/file.svg",
            url: "https://www.figma.com/",
          },
          {
            title: "GitHub",
            subtitle: "Code Platform",
            desc: "版本管理与工程协作基础设施。",
            cover: "/globe.svg",
            url: "https://github.com/",
          },
        ],
      },
      {
        group: "网站",
        items: [
          {
            title: "MDN Web Docs",
            subtitle: "Web 标准文档",
            desc: "最权威的 Web API 与规范实践资料。",
            cover: "/next.svg",
            url: "https://developer.mozilla.org/",
          },
          {
            title: "Can I Use",
            subtitle: "兼容性查询",
            desc: "前端特性在各浏览器中的支持情况。",
            cover: "/vercel.svg",
            url: "https://caniuse.com/",
          },
          {
            title: "CSS-Tricks",
            subtitle: "前端文章",
            desc: "CSS 与前端工程实践的长期内容库。",
            cover: "/file.svg",
            url: "https://css-tricks.com/",
          },
        ],
      },
    ],
  },
  progress: [
    { id: "P0", name: "基线冻结", weight: 5, status: "done" },
    { id: "P1", name: "内容盘点", weight: 10, status: "done" },
    { id: "P2", name: "内容模型化", weight: 10, status: "done" },
    { id: "P3", name: "模块内容落地", weight: 20, status: "done" },
    { id: "P4", name: "资源素材落地", weight: 10, status: "done" },
    { id: "P5", name: "响应式与可访问性", weight: 10, status: "done" },
    { id: "P6", name: "性能与SEO", weight: 10, status: "done" },
    { id: "P7", name: "全链路验收", weight: 10, status: "done" },
    { id: "P8", name: "发布与监控", weight: 10, status: "partial" },
    { id: "P9", name: "文档与交接", weight: 5, status: "done" },
  ],
};

export function calculateProgress(progressPhases) {
  return progressPhases.reduce((sum, phase) => {
    const rate = phase.status === "done" ? 1 : phase.status === "partial" ? 0.5 : 0;
    return sum + phase.weight * rate;
  }, 0);
}
