/** @type {import("../schema").BlogPost[]} */
export const blogPosts = [
  {
    title: "把 AI 真正接进日常创作",
    date: "2026-04-01",
    summary: "记录我怎样把检索、整理、初稿和复盘拆成可复用流程，让 AI 真的成为日常工作的一部分。",
    cover: "/assets/blog/blog-react.webp",
    url: "https://openai.com/",
    category: "AI",
    tags: ["AI", "工作流", "创作"],
  },
  {
    title: "AI 工作流的输入输出设计",
    date: "2026-03-15",
    summary: "比起不断叠加工具，我更关心输入格式、上下文组织和交付标准如何让结果稳定下来。",
    cover: "/assets/blog/blog-frontend.webp",
    url: "https://platform.openai.com/docs",
    category: "AI",
    tags: ["AI", "效率", "方法论"],
  },
  {
    title: "从钱包到签名：一次讲清 Web3 基础操作",
    date: "2026-03-01",
    summary: "把钱包、签名、授权和链上交互拆成几步看，Web3 的基础路径其实没有想象中那么绕。",
    cover: "/assets/blog/blog-nomad.webp",
    url: "https://ethereum.org/",
    category: "Web3",
    tags: ["Web3", "钱包", "基础"],
  },
  {
    title: "链上身份能不能成为长期内容资产",
    date: "2026-02-15",
    summary: "从所有权、公开可验证和可迁移性出发，梳理链上身份与长期写作之间真正有价值的连接点。",
    cover: "/assets/blog/blog-tech-life.webp",
    url: "https://ethereum.org/en/web3/",
    category: "Web3",
    tags: ["Web3", "身份", "内容"],
  },
  {
    title: "前端工程师也该懂的 DNS 与 HTTPS",
    date: "2026-02-01",
    summary: "把域名解析、证书、CDN 和缓存串成一条线，线上排障时就不会只盯着页面本身发呆。",
    cover: "/assets/blog/blog-performance.webp",
    url: "https://developers.cloudflare.com/dns/",
    category: "网络基础",
    tags: ["网络基础", "DNS", "HTTPS"],
  },
  {
    title: "家庭网络排障清单",
    date: "2026-01-20",
    summary: "整理光猫、路由器、Wi-Fi 干扰、DNS 与端口转发这些最常见的问题定位顺序，尽量少走弯路。",
    cover: "/assets/blog/blog-frontend.webp",
    url: "https://www.cloudflare.com/learning/dns/what-is-dns/",
    category: "网络基础",
    tags: ["网络基础", "排障", "家庭网络"],
  },
  {
    title: "一台创作主机的装机思路",
    date: "2026-01-10",
    summary: "从 CPU、显卡、内存、硬盘与散热预算出发，讨论一套更平衡而不是只堆参数的配置方式。",
    cover: "/assets/blog/blog-tech-life.webp",
    url: "https://www.tomshardware.com/",
    category: "电脑装机",
    tags: ["电脑装机", "硬件", "配置"],
  },
  {
    title: "显示器、键盘与桌面效率",
    date: "2025-12-26",
    summary: "长时间写作、剪辑和开发时，哪些外设升级真的能改变工作体验，哪些只是看起来更专业。",
    cover: "/assets/blog/blog-performance.webp",
    url: "https://www.rtings.com/monitor",
    category: "电脑装机",
    tags: ["电脑装机", "外设", "效率"],
  },
  {
    title: "技术与生活的平衡",
    date: "2025-12-12",
    summary: "从训练安排、创作节奏和时间块管理三个角度总结，怎样把深度工作和生活体验放在同一条主线上。",
    cover: "/assets/blog/blog-tech-life.webp",
    url: "https://www.strongerbyscience.com/",
    category: "运动健身",
    tags: ["运动健身", "节奏", "生活方式"],
  },
  {
    title: "恢复比训练更难：一周节奏记录",
    date: "2025-11-28",
    summary: "记录训练量、睡眠和工作强度如何互相牵制，以及我怎样调整每周节奏避免长期透支。",
    cover: "/assets/blog/blog-nomad.webp",
    url: "https://www.precisionnutrition.com/",
    category: "运动健身",
    tags: ["运动健身", "恢复", "训练"],
  },
  {
    title: "日常补剂怎么做减法",
    date: "2025-11-15",
    summary: "不追求堆满一桌瓶瓶罐罐，而是从目标、饮食结构和反馈出发，做更克制的补剂选择。",
    cover: "/assets/blog/blog-react.webp",
    url: "https://examine.com/",
    category: "营养补剂",
    tags: ["营养补剂", "补剂", "饮食"],
  },
  {
    title: "训练期饮食和补剂安排复盘",
    date: "2025-11-01",
    summary: "把蛋白质、碳水、肌酸和电解质的使用场景拆开看，减少跟风式补充带来的混乱。",
    cover: "/assets/blog/blog-performance.webp",
    url: "https://www.healthline.com/nutrition/sports-nutrition-guide",
    category: "营养补剂",
    tags: ["营养补剂", "训练", "恢复"],
  },
];
