/** @type {import("../schema").GameEntry[]} */
export const gameEntries = [
  {
    title: "Black Myth: Wukong",
    summary: "以中国神话为背景的动作角色扮演游戏。你将扮演“天命人”，揭开昔日英雄传奇背后的真相。",
    posterColor: "linear-gradient(135deg, #111827 0%, #3f2b16 52%, #f59e0b 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "It Takes Two",
    summary: "纯粹为合作设计的平台冒险游戏。通过多样化的玩法，讲述了一段关于修补家庭关系的感人故事。",
    cover: "/assets/games/it-takes-two.jpeg",
    posterColor: "linear-gradient(135deg, #f97316 0%, #fb7185 100%)",
    featuredOnHome: true,
    featuredOrder: 2,
  },
  {
    title: "Ghostrunner",
    summary: "第一人称视角的硬核赛博朋克动作游戏。动作迅猛，强调一击必杀的极限战斗体验。",
    posterColor: "linear-gradient(135deg, #0f172a 0%, #1d4ed8 50%, #22d3ee 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Titanfall 2",
    summary: "顶尖的第一人称射击游戏。讲述了铁驭与泰坦之间深厚的情感羁绊以及震撼的科幻战争。",
    posterColor: "linear-gradient(135deg, #1e3a8a 0%, #2563eb 58%, #f97316 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Hellblade: Senua's Sacrifice",
    summary: "深入探索精神疾病的心理动作游戏。跟随塞娜进入凯尔特神话的深渊，进行一场痛苦的救赎旅程。",
    posterColor: "linear-gradient(135deg, #111827 0%, #374151 48%, #6b7280 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Portal",
    summary: "Valve 开发的经典解谜游戏。利用传送门枪在空间中穿梭，挑战物理定律并面对 AI 的嘲讽。",
    posterColor: "linear-gradient(135deg, #e2e8f0 0%, #cbd5e1 55%, #fb923c 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "To the Moon",
    summary: "催泪向剧情神作。两名医生通过改变记忆，为一个垂死的老人完成去月球的最后心愿。",
    posterColor: "linear-gradient(135deg, #0f172a 0%, #312e81 52%, #93c5fd 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Journey",
    summary: "艺术化的禅意冒险游戏。在无垠的沙漠中独自旅行或与陌生人偶遇，体验纯粹的情感波动。",
    cover: "/assets/games/journey.jpeg",
    posterColor: "linear-gradient(135deg, #fbbf24 0%, #fb923c 55%, #fef3c7 100%)",
    featuredOnHome: true,
    featuredOrder: 9,
  },
  {
    title: "GRIS",
    summary: "绝美的平台解谜游戏。通过色彩的恢复，讲述女孩在痛苦中找回自我、克服心理创伤的过程。",
    cover: "/assets/games/gris.jpg",
    posterColor: "linear-gradient(135deg, #d1d5db 0%, #94a3b8 55%, #fbcfe8 100%)",
    featuredOnHome: true,
    featuredOrder: 1,
  },
  {
    title: "ABZU",
    summary: "唯美的深海潜水游戏。探索色彩斑斓的海底世界并与数以千计的生物互动，节奏宁静且治愈。",
    cover: "/assets/games/abzu.jpeg",
    posterColor: "linear-gradient(135deg, #0f766e 0%, #0891b2 55%, #67e8f9 100%)",
    featuredOnHome: true,
    featuredOrder: 8,
  },
  {
    title: "THE FINALS",
    summary: "全场景可破坏的快节奏射击游戏。玩家在虚拟竞技场中竞技，极度强调地形破坏与战术搭配。",
    cover: "/assets/games/the-finals.jpg",
    posterColor: "linear-gradient(135deg, #b91c1c 0%, #ef4444 55%, #f97316 100%)",
    featuredOnHome: true,
    featuredOrder: 3,
  },
  {
    title: "Brotato",
    summary: "顶级俯视角竞技场射击轻度 Rogue 游戏。玩家扮演一只可同时手持 6 种武器的土豆，在异星怪物的包围中生存。",
    posterColor: "linear-gradient(135deg, #92400e 0%, #d97706 55%, #facc15 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Patrick's Parabox",
    summary: "屡获殊荣的递归解谜游戏。将“推箱子”机制推向极致，玩家在无限循环的逻辑空间中进出箱体。",
    cover: "/assets/games/parabox.jpeg",
    posterColor: "linear-gradient(135deg, #166534 0%, #10b981 55%, #a7f3d0 100%)",
    featuredOnHome: true,
    featuredOrder: 7,
  },
  {
    title: "Getting Over It with Bennett Foddy",
    summary: "极具挫败感的物理攀爬游戏。玩家仅靠一把长柄榔头操控瓮中人，在重力与物理碰撞的折磨下登顶。",
    posterColor: "linear-gradient(135deg, #1f2937 0%, #4b5563 55%, #9ca3af 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Raft",
    summary: "海上生存冒险游戏。玩家从一小块木板开始，通过打捞垃圾、扩建木筏，在危机四伏的大海中建立家园。",
    posterColor: "linear-gradient(135deg, #0369a1 0%, #0ea5e9 55%, #7dd3fc 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "URBO",
    summary: "极简风格的禅意城市建设解谜游戏。通过在方格盘上组合房屋使建筑升级，在轻快节奏中规划微缩都市。",
    posterColor: "linear-gradient(135deg, #e5e7eb 0%, #cbd5e1 55%, #93c5fd 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "The Forest",
    summary: "经典恐怖生存游戏。玩家在坠机后落入神秘森林，必须伐木建房、狩猎求生，并对抗潜伏的变异食人族。",
    posterColor: "linear-gradient(135deg, #14532d 0%, #166534 55%, #4d7c0f 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "FAR: Lone Sails",
    summary: "具有末世氛围的载具旅行游戏。玩家驾驶巨大的混合动力车在干涸海床上逆风而行，探寻文明遗迹。",
    posterColor: "linear-gradient(135deg, #78350f 0%, #d97706 55%, #fde68a 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Chained Together",
    summary: "多人协作攀爬游戏。玩家们被铁链锁在一起，必须同步跳跃与攀爬以逃离地狱，极度考验团队默契。",
    posterColor: "linear-gradient(135deg, #312e81 0%, #6366f1 55%, #c4b5fd 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "World of Goo",
    summary: "经典物理益智游戏。利用各种属性的“粘粘球”搭建桥梁或塔楼，通过力学设计将球送入管道。",
    cover: "/assets/games/world-of-goo.jpeg",
    posterColor: "linear-gradient(135deg, #111827 0%, #1f2937 55%, #f59e0b 100%)",
    featuredOnHome: true,
    featuredOrder: 4,
  },
  {
    title: "Sable",
    summary: "独特的莫比乌斯画风开放世界冒险游戏。玩家扮演名为沙贝的少女，穿梭于广袤的沙漠与古老残骸之间，展开一场关于自我发现的成年礼。",
    cover: "/assets/games/sable.jpeg",
    posterColor: "linear-gradient(135deg, #f5d0b5 0%, #f8dcc7 55%, #fef3c7 100%)",
    featuredOnHome: true,
    featuredOrder: 5,
  },
  {
    title: "OUROS",
    summary: "平静柔和的曲线拼图游戏。玩家通过拖动节点改变曲线路径，让光球顺利通过所有目标点，极具美感。",
    posterColor: "linear-gradient(135deg, #0f766e 0%, #22d3ee 55%, #ecfeff 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Hook / Hook 2",
    summary: "极简主义逻辑解谜系列。玩家需按正确顺序拆解由钩子、连线和机关组成的复杂结构，过程解压。",
    posterColor: "linear-gradient(135deg, #f8fafc 0%, #cbd5e1 55%, #64748b 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "The Henry Stickmin Collection",
    summary: "互动式动画冒险合集。通过无厘头的选择引导主角亨利完成任务，包含大量爆笑死法与致敬彩蛋。",
    posterColor: "linear-gradient(135deg, #be123c 0%, #ef4444 55%, #fecaca 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Buckshot Roulette",
    summary: "高风险桌面赌博游戏。在阴暗后巷与恶魔对赌，使用改制散弹枪进行生死角逐，心理战极强。",
    posterColor: "linear-gradient(135deg, #052e16 0%, #166534 55%, #65a30d 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "LIMBO",
    summary: "黑白剪影风格解谜平台游戏。玩家扮演小男孩在充满陷阱和巨大生物的阴森世界寻找姐姐，气氛压抑。",
    posterColor: "linear-gradient(135deg, #020617 0%, #334155 55%, #94a3b8 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "12 is Better Than 6",
    summary: "钢笔画风格的硬核俯视角射击游戏。以 1873 年美国西部为背景，强调精准击杀与潜行，小众精品。",
    posterColor: "linear-gradient(135deg, #451a03 0%, #92400e 55%, #fcd34d 100%)",
    featuredOnHome: false,
    featuredOrder: null,
  },
  {
    title: "Hue",
    summary: "着色解谜平台游戏。玩家通过改变世界背景颜色使障碍物显现或消失，在灰色世界中寻找失踪的母亲。",
    cover: "/assets/games/hue.jpeg",
    posterColor: "linear-gradient(135deg, #ef4444 0%, #f59e0b 24%, #eab308 40%, #22c55e 58%, #06b6d4 78%, #8b5cf6 100%)",
    featuredOnHome: true,
    featuredOrder: 6,
  },
];
